version: '0'
services:
  orange-api-app:
    build: .
    container_name: orange-api-app
    ports:
      - "8000:80"
    environment:
      - ENV=development
    volumes:
      - .:/app
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload" ]
